name: CI
on:
  workflow_dispatch:

jobs:
  myFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: Say Hello
        run: echo 'Hello World !!'
      - name: Show Files
        run: ls
